apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: vault-app
  namespace: demo
spec:
  clientConfig:
    url: http://vault.default.svc:8200
  parameters:
    serviceAccountName: policy-admin
    vaultRole: policy-admin-role
    path: kubernetes
