apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-mdb
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: vault-mdb-storage