apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-kv
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: vault-kv-storage